server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: saa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    show-sql: true
  flyway:
    schemas: catalog
